server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: hoyoverse-coupon-scraper
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: false
      write-dates-as-timestamps: false
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"

logging:
  level:
    com.genshin.couponscraper: INFO
    org.springframework.web: WARN
    org.jsoup: WARN
    root: WARN
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never